### ISSUE TITLE
Initial User Works Great: New user has my dock + Apple dock icons

### ISSUE THREAD

**Issue by dannyhanes** [Error-freeIT/Dock-Master#6]
When I create and deploy a package, the dock is configured perfectly for the currently signed in user. 

However when I create a new user and log in, I get the dock I configured along with other Apple dock icons. Is there anyway to prevent this? Did I miss a step?

**Comment by Error-freeIT** [comment]
The additional Apple apps (Maps, Photos, iBooks) are likely due to "add-app" and "add-doc" sections in "/System/Library/CoreServices/Dock.app/Contents/Resources/com.apple.dockfixup.plist". Before the introduction of System Integrity Protection (SIP) in 10.11, Dock Master packages would remove those entries, unfortunately this is no longer an option. Either use a profile (no removable dock items) or run the Dock Master package after the user has logged in.

**Comment by dannyhanes** [comment]
@Error-freeIT Do you happen to have a pro-tip for running the pkg after the user logs in?

**Comment by Error-freeIT** [comment]
[Outset](https://github.com/chilcote/outset) should do the job.

**Comment by dannyhanes** [comment]
@Error-freeIT That is a fantastic tip. I had heard of Outset, but never found a need to look into it... until now. Thanks for the quick replies!
